### ISSUE TITLE
 Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by mahramane** [timhuang1018/Krop#15]
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
                                                                                                    	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:731)
                                                                                                    	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:81)
                                                                                                    	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:121)
                                                                                                    	at android.graphics.Canvas.drawBitmap(Canvas.java:1615)
                                                                                                    	at coil3.BitmapImage.draw(Image.android.kt:65)
                                                                                                    	at coil3.Image_androidKt.toBitmap(Image.android.kt:43)
                                                                                                    	at coil3.Image_androidKt.toBitmap(Image.android.kt:28)
                                                                                                    	at coil3.Image_androidKt.toBitmap$default(Image.android.kt:24)
                                                                                                    	at io.keeppro.Krop.crop(Krop.kt:18)
                                                                                                    	at io.keeppro.CroppableState.crop(CroppableState.kt:242)

**Comment by timhuang1018** [comment]
hi @mahramane , this is a known issue for coil of rendering issue particularly on Android, you could find workaround and discussion at https://github.com/coil-kt/coil/issues/159. I have same workaround in [my sample](https://github.com/timhuang1018/Krop/blob/main/sample-multiplatform/src/androidMain/kotlin/io/keeppro/krop/Utils.android.kt) as well
